Reorganize package and update dependencies
BREADING CHANGE: the `gocovcheck` executable is now in a separate subpackage
`gocovcheck/gocovcheck`, and no longer at the top level.

- Development environment no longer requires parent directory setup, and can be
  done entirely within the git checkout.

- Updated `goconvey` to version 1.7.2. In particular, this requires minimum Go
  version 1.16.

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2017 Sergey Berezin
+# Copyright 2022 Sergey Berezin
 
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -14,70 +14,92 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-source "${DIR}/common.sh"
 
-cd "${DIR}"
+# Stop the script on the first error.
+trap 'runtests failed on line ${LINENO}"; exit 1' ERR
 
-source "${ROOT}/bin/activate"
+ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+cd "${ROOT}"
 
-modules=("." "./coverage" "./jsonread")
+echo "Activating Go environment in ${ROOT}"
+source "${ROOT}/gopath/bin/bashrc"
 
-COVERAGE_PROFILE=".coverage"
+PACKAGES=($@)
+
+if [ "$TEST_RECORD" = "1" ]; then
+    echo "*** Running tests in RECORD mode ***"
+fi
+
+echo "GOROOT: `go env GOROOT`"
+echo "GOPATH: `go env GOPATH`"
+
+COVERAGE_PROFILE="${ROOT}/.coverage"
 COVERAGERC=".coveragerc"
-MIN_COVERAGE=75
+COVERAGE_HTML="coverage.html"
+DEFAULT_MIN_COVERAGE=75
 
-tests_failed=()
-coverage_low=()
+tests_failed=0
+coverage_low=0
+code_warnings=()
 rm -f "$COVERAGE_PROFILE"
-for path in "${modules[@]}"; do
-    echo "testing module '$path' in `pwd`"
-    for pkg in $(cd "$path"; go list); do
-	echo "testing package $pkg"
-	if ! go test -coverprofile "${COVERAGE_PROFILE}_tmp" "$pkg"; then
-	    tests_failed=("${tests_failed[@]}" "$pkg")
-	fi
-	if [ -f "${pkg}/${COVERAGERC}" ]; then
-	    min_coverage=`jsonread "${pkg}/${COVERAGERC}" min_coverage "$MIN_COVERAGE"`
-	else
-	    min_coverage="$MIN_COVERAGE"
-	fi
-	if [ -f "${COVERAGE_PROFILE}_tmp" ]; then
-	    if ! gocovcheck "${COVERAGE_PROFILE}_tmp" "$min_coverage"; then
-		coverage_low=("${coverage_low[@]}" "$pkg")
-	    fi
-	    cat "${COVERAGE_PROFILE}_tmp" >> "$COVERAGE_PROFILE"
-	    rm -f "${COVERAGE_PROFILE}_tmp"
-	fi
-    done
-done
+GOTEST_ARGS=()
 
-if [ -f "$COVERAGE_PROFILE" ]; then
-    echo "Overall coverage:"
-    if ! gocovcheck "$COVERAGE_PROFILE" "$MIN_COVERAGE"; then
-	coverage_low=("${coverage_low[@]}" "Average across all packages")
+if ! go test -coverprofile "${COVERAGE_PROFILE}" "${GOTEST_ARGS[@]}" "${PACKAGES[@]}"; then
+	tests_failed=1
+fi
+go tool cover -html="${COVERAGE_PROFILE}" -o "${COVERAGE_HTML}"
+echo "Wrote ${ROOT}/${COVERAGE_HTML} - open in a browser to see coverage."
+if [ -f "${ROOT}/${COVERAGERC}" ]; then
+	min_coverage=`jsonread "${ROOT}/${COVERAGERC}" min_coverage "$DEFAULT_MIN_COVERAGE"`
+else
+	min_coverage="$DEFAULT_MIN_COVERAGE"
+fi
+
+if ! go vet "${PACKAGES[@]}"; then
+	code_warnings=("${code_warnings[@]}" "go vet has warnings")
+fi
+# golint returns code 0 even when it fails. We'd have to check its output,
+# and run it again to print warnings to stdout.
+if [[ ! -z $(golint "${PACKAGES[@]}") ]] ; then
+	code_warnings=("${code_warnings[@]}" "golint has warnings")
+	golint "${PACKAGES[@]}"
+fi
+if [ ! -z $(gofmt -l -s "${PACKAGES[@]}") ]; then
+	echo "WARNING: the following files are not formatted correctly:"
+	gofmt -l -s .
+	echo "Please run 'make gofmt'."
+	code_warnings=("${code_warnings[@]}" "need to run 'make gofmt'")
+fi
+
+if [ -f "${ROOT}/${COVERAGERC}" ] && [ -f "$COVERAGE_PROFILE" ]; then
+    global_min_coverage=`jsonread "${ROOT}/${COVERAGERC}" min_coverage "$DEFAULT_MIN_COVERAGE"`
+    if ! gocovcheck "$COVERAGE_PROFILE" "$global_min_coverage"; then
+	coverage_low=1
     fi
 fi
-echo "got here"
-go vet "${modules[@]}"
-golint "${modules[@]}"
 
 exit_code=0
 
-if [ ${#tests_failed[@]} -ne 0 ]; then
-    echo "Tests failed in packages:"
-    for pkg in "${tests_failed[@]}"; do
-	echo "  $pkg"
+if [ ${tests_failed} -ne 0 ]; then
+    echo "Tests failed."
+    exit_code=1
+fi
+
+if [ ${coverage_low} -ne 0 ]; then
+    echo "Insufficient coverage."
+    exit_code=1
+fi
+
+if [ ${#code_warnings[@]} -ne 0 ]; then
+    echo "Code quality:"
+    for msg in "${code_warnings[@]}"; do
+	echo "  $msg"
     done
     exit_code=1
 fi
 
-if [ ${#coverage_low[@]} -ne 0 ]; then
-    echo "Insufficient coverage in packages:"
-    for pkg in "${coverage_low[@]}"; do
-	echo "  $pkg"
-    done
-    exit_code=1
+if [ $exit_code -eq 0 ]; then
+    echo "Tests pass."
 fi
 
 exit "$exit_code"
